server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/security_app
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 