server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net/heroku_da81db2f9da3483
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USER}
    password: ${PASSWORD}
